eu_analytics_databricks:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: eu_catalog
      schema: analytics
      host: "{{ env_var('DATABRICKS_EU_HOST') }}"
      http_path: /sql/1.0/warehouses/your-warehouse-id
      token: "{{ env_var('DATABRICKS_EU_TOKEN') }}"
      threads: 4
