name: 'us_analytics_dbt'
version: '1.0.0'
config-version: 2

profile: 'us_analytics_databricks'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  us_analytics_dbt:
    silver:
      materialized: incremental
    gold:
      materialized: table
